server.port=${PORT:8080}
spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://sakthivelv202222:jBI8AWBqHPXXu4bx@cluster0.vsfhi.mongodb.net/capstonedatabase?retryWrites=true&w=majority&appName=Cluster0

