server.port=${PORT:8080}
spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://sakthivelv202222:jBI8AWBqHPXXu4bx@cluster0.vsfhi.mongodb.net/capstonedatabase?retryWrites=true&w=majority&appName=Cluster0


# EMAIL_USER=sakthivelv202222@gmail.com
# EMAIL_PASS=vjrriqtisknjfucn


# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sakthivelv202222@gmail.com
spring.mail.password=vjrriqtisknjfucn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000