server.port=${PORT:8080}
spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://sakthivelv202222:jBI8AWBqHPXXu4bx@cluster0.vsfhi.mongodb.net/capstonedatabase?retryWrites=true&w=majority&appName=Cluster0


# EMAIL_USER=sakthivelv202222@gmail.com
# EMAIL_PASS=vjrriqtisknjfucn


# xsmtpsib-0747fdf0f50b0ffd231977e8d828adbbebdd9d550d9dc14510bb9a4852607a50-oP0q2TmET9hp5nn6


# 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
BREVO_API_KEY=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

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=97d79b001@smtp-brevo.com


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000